config/routes.rb
Rails.application.routes.draw do

  root 'catalogs#index', as:'root'

  get 'api' => 'api#list_catalog'
  get 'apis' => 'api#list_catalog'
  get 'list_catalog' => 'api#list_catalog'
  get 'api/:id' => 'api#list_product'
  get 'apis/:id' => 'api#list_product'
  get 'list_product/:id' => 'api#list_product'
  resources :api, only:[:list_catalog, :list_product]
  resources :api do
    get 'list_catalog', on: :collection
    get 'list_product', on: :member
  end
  resources :products
  resources :catalogs
  get '*path', to: 'catalogs#index'

end

app/models/catalog.rb
class Catalog < ActiveRecord::Base
  has_many :products, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
end

app/models/common_methods.rb
module CommonMethods

  def it_is_api?
    controller_name == API_CONTROLLER
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :catalog
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true, :numericality => {:greater_than => 0}

  def self.empty(id)
    {name: 'empty', description:'no such product', price:0, catalog_id: id}
  end
end

app/models/seed.rb
class Seed < ActiveRecord::Base

end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  layout nil

  def list_catalog
    render json: Catalog.all
  end

  def list_product
    render json: Catalog.find(params[:id]).products
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include CommonMethods
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from ActionController::RoutingError, :with => :send_empty_record
  rescue_from ActionController::BadRequest, :with => :send_empty_record
  rescue_from ActionController::RenderError, :with => :send_empty_record
  rescue_from ActionController::MethodNotAllowed, :with => :send_empty_record
  rescue_from ActionController::UnknownFormat, :with => :send_empty_record
  rescue_from ActiveRecord::RecordNotFound, :with => :send_empty_record
  rescue_from ActionController::UnknownController, :with => :go_to_root
  rescue_from ActiveRecord::RecordNotSaved, :with => :go_to_root

  def save_invalid_data(obj)
    Seed.create(addr: request.remote_ip, obj_hash: obj.to_s, name: obj.errors.messages.to_s)
  end

  def send_empty_record
    if it_is_api?
      render json: Product.empty(params[:id])
    else
      go_to_root
    end
  end

  def go_to_root
    redirect_to root_url
  end
end

app/controllers/catalogs_controller.rb
class CatalogsController < ApplicationController
  def index
    @catalogs = Catalog.all
  end

  def new
    @catalog = Catalog.new
  end

  def edit
    @catalog = Catalog.find_by_id(params[:id])
  end

  def create
    @catalog = Catalog.create(catalog_params)
    if @catalog.valid?
      redirect_to catalogs_path
    else
      flash[:notice] = 'Ошибка ' + @catalog.errors.messages.to_s + ' добавлна в Seeds'
      save_invalid_data(@catalog)
      redirect_to new_catalog_path
    end
  end

  def show
    @catalog = Catalog.find(params[:id])
    @products = @catalog.products
  end

  def update
    @catalog = Catalog.find(params[:id])
    if @catalog.update_attributes(catalog_params)
      redirect_to catalogs_path
    else
      flash[:notice] = 'No updated Catalog '+ @catalog.id.to_s
      redirect_to edit_catalog_path
    end
  end

  def destroy
    @catalog = Catalog.find(params[:id]).destroy
    redirect_to catalogs_path
  end

  private
  def catalog_params
    params.require(:catalog).permit(:name, :description)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @catalog = Catalog.find(params[:id])
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
    @catalog = Catalog.find(@product.catalog_id)
  end

  def create
    id = params[:product][:catalog_id]
    @product = Product.create(product_params)
    if @product.valid?
      redirect_to catalog_path(@product.catalog_id)
    else
      flash[:notice] = 'Ошибка ' + @product.errors.messages.to_s + ' добавлна в Seeds'
      save_invalid_data(@product)
      redirect_to catalog_path(id)
    end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to catalog_path(@product.catalog_id)
    else
      flash[:notice] = 'No updated Product '+ @product.id.to_s
      redirect_to :back
    end
  end

  def destroy
    @product = Product.find(params[:id]).destroy
    redirect_to :back
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price, :catalog_id)
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catalogs_helper.rb
module CatalogsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/catalogs/edit.html.erb
<h1>Измените название и описание каталога</h1>
<%= render partial: 'shared/catalog_form'%>

app/views/catalogs/index.html.erb
<h1>Список каталогов</h1>
<% if @catalogs.empty? || @catalogs.nil? %>
    <h2>Нет данных в БД</h2>
<% else %>
    <table>
        <% @catalogs.each do |i| %>
            <tr>
                <td class="id"><%= i.id %></td>
                <td class="name"><%= i.name %></td>
                <td class="full"><%= i.description %></td>
                <td class="symbol"><%= link_to 'Содержание', catalog_path(i) %></td>
                <td class="symbol"><%= link_to 'Редактировать', edit_catalog_path(i) %></td>
                <td class="symbol"><%= link_to 'Удалить', i,method: :delete, data: { confirm: "Are you sure?" }  %></td>
            </tr>
        <% end %>
    </table>
<% end %>
<%= link_to 'Добавить новый каталог', new_catalog_path %> <br>
<%= link_to 'Список всех продуктов', products_path %>

app/views/catalogs/new.html.erb
<h1>Введите название и описание каталога</h1>
<%= render partial: 'shared/catalog_form'%>

app/views/catalogs/show.html.erb
<h2>Каталог</h2>
<h2 class="name"><%= @catalog.name %></h2>
<h2>Список продуктов</h2>
<%= render partial: 'shared/products_list' %>
<%= link_to 'Добавить новый продукт в каталог', product_path(@catalog.id) %> <br>
<%= link_to 'Список всех каталогов', catalogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestTarifer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
<% flash.each do |name, msg| %>
    <h2> <%= content_tag :div, msg, :id => "flash_#{name}" %></h2>
<% end %>
</body>
</html>

app/views/products/edit.html.erb
<h1>Отредактируйте продукт</h1>
<%= render partial: 'shared/product_form' %>

app/views/products/index.html.erb
<h1>Список продуктов</h1>
<%= render partial: 'shared/products_list' %>
<%= link_to 'Список всех каталогов', catalogs_path %>

app/views/products/show.html.erb
<h2>Каталог</h2>
<h2 class="name"><%= @catalog.name %></h2>
<h2>Список продуктов</h2>
<%= render partial: 'shared/product_form' %>

app/views/shared/_catalog_form.html.erb
<%= form_for @catalog do |f| %>
    <table>
      <tr>
        <td>Название:</td>
        <td><%= f.text_field :name, size: "51" %></td>
      </tr>
      <tr>
        <td>Описание:</td>
        <td><%= f.text_area :description, size: "50x3" %></td>
      </tr>
    </table>
    <%= f.submit 'Сохранить'%>
    <%= link_to 'Отменить', controller: 'catalogs', action: 'index' %>
<%end%>

app/views/shared/_product_form.html.erb
<%= form_for @product do |f| %>
    <table>
      <tr>
        <td>Название:</td>
        <td><%= f.text_field :name, size: "51" %></td>
      </tr>
      <tr>
        <td>Описание:</td>
        <td><%= f.text_area :description, size: "50x3" %></td>
      </tr>
      <tr>
        <td>Цена:</td>
        <td><%= f.number_field :price, min: 0.00, step:0.01 %></td>
      </tr>
      <%= f.hidden_field(:catalog_id, :value=>@catalog.id ) %>
    </table>
    <%= f.submit 'Сохранить'%>
    <%= link_to 'Отменить', controller: 'catalogs', action: 'index' %>
<%end%>

app/views/shared/_products_list.html.erb
<% if @products.empty?  || @products.nil? %>
    <h2>Нет данных в БД</h2>
<% else %>
    <table>
      <% @products.each do |i| %>
          <tr>
            <td class="id"><%= i.id %></td>
            <td class="name"><%= i.name %></td>
            <td class="full"><%= i.description %></td>
            <td class="symbol"><%= link_to 'Редактировать', edit_product_path(i) %></td>
            <td class="symbol"><%= link_to 'Удалить', i,method: :delete, data: { confirm: "Are you sure?" }  %></td>
          </tr>
      <% end %>
    </table>
<% end %>